<?php

/* custom routes generated by CRUD */


Route::group(array('prefix' => 'admin/cardImport/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.cardImport.'), function () {

Route::get('cardimports', ['as'=> 'cardimports.index', 'uses' => 'Card_Import\CardimportController@index']);
Route::post('cardimports', ['as'=> 'cardimports.store', 'uses' => 'Card_Import\CardimportController@store']);
Route::get('cardimports/create', ['as'=> 'cardimports.create', 'uses' => 'Card_Import\CardimportController@create']);
Route::put('cardimports/{cardimports}', ['as'=> 'cardimports.update', 'uses' => 'Card_Import\CardimportController@update']);
Route::patch('cardimports/{cardimports}', ['as'=> 'cardimports.update', 'uses' => 'Card_Import\CardimportController@update']);
Route::get('cardimports/{id}/delete', ['as' => 'cardimports.delete', 'uses' => 'Card_Import\CardimportController@getDelete']);
Route::get('cardimports/{id}/confirm-delete', ['as' => 'cardimports.confirm-delete', 'uses' => 'Card_Import\CardimportController@getModalDelete']);
Route::get('cardimports/{cardimports}', ['as'=> 'cardimports.show', 'uses' => 'Card_Import\CardimportController@show']);
Route::get('cardimports/{cardimports}/edit', ['as'=> 'cardimports.edit', 'uses' => 'Card_Import\CardimportController@edit']);

});


Route::group(array('prefix' => 'admin/cardStatus/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.cardStatus.'), function () {

Route::get('cardstatuses', ['as'=> 'cardstatuses.index', 'uses' => 'Card_Status\CardstatusController@index']);
Route::post('cardstatuses', ['as'=> 'cardstatuses.store', 'uses' => 'Card_Status\CardstatusController@store']);
Route::get('cardstatuses/create', ['as'=> 'cardstatuses.create', 'uses' => 'Card_Status\CardstatusController@create']);
Route::put('cardstatuses/{cardstatuses}', ['as'=> 'cardstatuses.update', 'uses' => 'Card_Status\CardstatusController@update']);
Route::patch('cardstatuses/{cardstatuses}', ['as'=> 'cardstatuses.update', 'uses' => 'Card_Status\CardstatusController@update']);
Route::get('cardstatuses/{id}/delete', ['as' => 'cardstatuses.delete', 'uses' => 'Card_Status\CardstatusController@getDelete']);
Route::get('cardstatuses/{id}/confirm-delete', ['as' => 'cardstatuses.confirm-delete', 'uses' => 'Card_Status\CardstatusController@getModalDelete']);
Route::get('cardstatuses/{cardstatuses}', ['as'=> 'cardstatuses.show', 'uses' => 'Card_Status\CardstatusController@show']);
Route::get('cardstatuses/{cardstatuses}/edit', ['as'=> 'cardstatuses.edit', 'uses' => 'Card_Status\CardstatusController@edit']);

});


Route::group(array('prefix' => 'admin/vendor/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.vendor.'), function () {

Route::get('vendors', ['as'=> 'vendors.index', 'uses' => 'Vendor\VendorController@index']);
Route::post('vendors', ['as'=> 'vendors.store', 'uses' => 'Vendor\VendorController@store']);
Route::get('vendors/create', ['as'=> 'vendors.create', 'uses' => 'Vendor\VendorController@create']);
Route::put('vendors/{vendors}', ['as'=> 'vendors.update', 'uses' => 'Vendor\VendorController@update']);
Route::patch('vendors/{vendors}', ['as'=> 'vendors.update', 'uses' => 'Vendor\VendorController@update']);
Route::get('vendors/{id}/delete', ['as' => 'vendors.delete', 'uses' => 'Vendor\VendorController@getDelete']);
Route::get('vendors/{id}/confirm-delete', ['as' => 'vendors.confirm-delete', 'uses' => 'Vendor\VendorController@getModalDelete']);
Route::get('vendors/{vendors}', ['as'=> 'vendors.show', 'uses' => 'Vendor\VendorController@show']);
Route::get('vendors/{vendors}/edit', ['as'=> 'vendors.edit', 'uses' => 'Vendor\VendorController@edit']);

});


Route::group(array('prefix' => 'admin/vendorStatus/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.vendorStatus.'), function () {

Route::get('vendorStatuses', ['as'=> 'vendorStatuses.index', 'uses' => 'Vendorstatus\VendorStatusController@index']);
Route::post('vendorStatuses', ['as'=> 'vendorStatuses.store', 'uses' => 'Vendorstatus\VendorStatusController@store']);
Route::get('vendorStatuses/create', ['as'=> 'vendorStatuses.create', 'uses' => 'Vendorstatus\VendorStatusController@create']);
Route::put('vendorStatuses/{vendorStatuses}', ['as'=> 'vendorStatuses.update', 'uses' => 'Vendorstatus\VendorStatusController@update']);
Route::patch('vendorStatuses/{vendorStatuses}', ['as'=> 'vendorStatuses.update', 'uses' => 'Vendorstatus\VendorStatusController@update']);
Route::get('vendorStatuses/{id}/delete', ['as' => 'vendorStatuses.delete', 'uses' => 'Vendorstatus\VendorStatusController@getDelete']);
Route::get('vendorStatuses/{id}/confirm-delete', ['as' => 'vendorStatuses.confirm-delete', 'uses' => 'Vendorstatus\VendorStatusController@getModalDelete']);
Route::get('vendorStatuses/{vendorStatuses}', ['as'=> 'vendorStatuses.show', 'uses' => 'Vendorstatus\VendorStatusController@show']);
Route::get('vendorStatuses/{vendorStatuses}/edit', ['as'=> 'vendorStatuses.edit', 'uses' => 'Vendorstatus\VendorStatusController@edit']);

});


Route::group(array('prefix' => 'admin/cardrequisition/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.cardrequisition.'), function () {

Route::get('cardrequisitions', ['as'=> 'cardrequisitions.index', 'uses' => 'Cardrequisition\CardrequisitionController@index']);
Route::post('cardrequisitions', ['as'=> 'cardrequisitions.store', 'uses' => 'Cardrequisition\CardrequisitionController@store']);
Route::get('cardrequisitions/create', ['as'=> 'cardrequisitions.create', 'uses' => 'Cardrequisition\CardrequisitionController@create']);
Route::put('cardrequisitions/{cardrequisitions}', ['as'=> 'cardrequisitions.update', 'uses' => 'Cardrequisition\CardrequisitionController@update']);
Route::patch('cardrequisitions/{cardrequisitions}', ['as'=> 'cardrequisitions.update', 'uses' => 'Cardrequisition\CardrequisitionController@update']);
Route::get('cardrequisitions/{id}/delete', ['as' => 'cardrequisitions.delete', 'uses' => 'Cardrequisition\CardrequisitionController@getDelete']);
Route::get('cardrequisitions/{id}/confirm-delete', ['as' => 'cardrequisitions.confirm-delete', 'uses' => 'Cardrequisition\CardrequisitionController@getModalDelete']);
Route::get('cardrequisitions/{cardrequisitions}', ['as'=> 'cardrequisitions.show', 'uses' => 'Cardrequisition\CardrequisitionController@show']);
Route::get('cardrequisitions/{cardrequisitions}/edit', ['as'=> 'cardrequisitions.edit', 'uses' => 'Cardrequisition\CardrequisitionController@edit']);

});


Route::group(array('prefix' => 'admin/cardrequisitionStatus/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.cardrequisitionStatus.'), function () {

Route::get('cardrequisitionStatuses', ['as'=> 'cardrequisitionStatuses.index', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@index']);
Route::post('cardrequisitionStatuses', ['as'=> 'cardrequisitionStatuses.store', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@store']);
Route::get('cardrequisitionStatuses/create', ['as'=> 'cardrequisitionStatuses.create', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@create']);
Route::put('cardrequisitionStatuses/{cardrequisitionStatuses}', ['as'=> 'cardrequisitionStatuses.update', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@update']);
Route::patch('cardrequisitionStatuses/{cardrequisitionStatuses}', ['as'=> 'cardrequisitionStatuses.update', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@update']);
Route::get('cardrequisitionStatuses/{id}/delete', ['as' => 'cardrequisitionStatuses.delete', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@getDelete']);
Route::get('cardrequisitionStatuses/{id}/confirm-delete', ['as' => 'cardrequisitionStatuses.confirm-delete', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@getModalDelete']);
Route::get('cardrequisitionStatuses/{cardrequisitionStatuses}', ['as'=> 'cardrequisitionStatuses.show', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@show']);
Route::get('cardrequisitionStatuses/{cardrequisitionStatuses}/edit', ['as'=> 'cardrequisitionStatuses.edit', 'uses' => 'Cardrequisition_Status\CardrequisitionStatusController@edit']);

});


Route::group(array('prefix' => 'admin/comments/','namespace' => 'Admin','middleware' => 'admin','as'=>'admin.comments.'), function () {

Route::get('comments', ['as'=> 'comments.index', 'uses' => 'Comments\CommentsController@index']);
Route::post('comments', ['as'=> 'comments.store', 'uses' => 'Comments\CommentsController@store']);
Route::get('comments/create', ['as'=> 'comments.create', 'uses' => 'Comments\CommentsController@create']);
Route::put('comments/{comments}', ['as'=> 'comments.update', 'uses' => 'Comments\CommentsController@update']);
Route::patch('comments/{comments}', ['as'=> 'comments.update', 'uses' => 'Comments\CommentsController@update']);
Route::get('comments/{id}/delete', ['as' => 'comments.delete', 'uses' => 'Comments\CommentsController@getDelete']);
Route::get('comments/{id}/confirm-delete', ['as' => 'comments.confirm-delete', 'uses' => 'Comments\CommentsController@getModalDelete']);
Route::get('comments/{comments}', ['as'=> 'comments.show', 'uses' => 'Comments\CommentsController@show']);
Route::get('comments/{comments}/edit', ['as'=> 'comments.edit', 'uses' => 'Comments\CommentsController@edit']);

});
